### ISSUE TITLE
Decode behavior change with custom type

### ISSUE THREAD

**Issue by element-of-surprise** [go-json-experiment/json#101]
This is a new bug based on an older bug I created that seemed like the issue wasn't a v1 to v2 behavior change and was closed.  

I believe this to be a behavior change. The following snippets are the same encode/decode scenario, only differing if using v1 or v2.

Here is v1 behavior(works):
https://go.dev/play/p/8TCLcNznOdu

Here is v2 behavior(doesn't work):
https://go.dev/play/p/ZSlqMAwQjX0

This might not be something you want to support, but I believe this to be a behavior change from v1 to v2.  Feel free to close it, but I wanted to make sure this is a conscious decision on your part and not because my bug wasn't clear.

Here is the original issue: https://github.com/go-json-experiment/json/issues/36

**Comment by dsnet** [comment]
I apologize we missed the main intent of your original issue. I think the red herring is that it focused more on the marshal side of things, when the divergence in behavior is on the unmarshal side.

This was indeed a deliberate change in v2 behavior. In order to serialize `[]Category` as base64, the "json" package was relying on an undocumented bug in Go reflection. In particular, Go reflection is supposed to be an API that mimics the Go language itself. Just as how you are [not allowed to convert a `[]Category` into a `[]byte` directly](https://go.dev/play/p/XiZyXjOmN1_u) (because the types are invariant), so also should you not be able to do so in Go reflection. However, due to a bug in Go reflection, this is currently permitted, but not something guaranteed to be permitted in the future. In v2, we do not want to rely on bugs in Go reflection, so we disallowed this use case by default.

You can mimic the v1 behavior by using the `FormatBytesWithLegacySemantics` option.
https://go.dev/play/p/ik6I9sjJ7l2

**Comment by element-of-surprise** [comment]
Thank you Joe, nothing to apologize for.  This package is great and I appreciate your time.

I'm sorry I was not clear enough in the original bug.  

I'm closing this now.
