### ISSUE TITLE
json: cannot unmarshal JSON array into Go value of type [2]uint8

### ISSUE THREAD

**Issue by mewmew** [go-json-experiment/json#58]
Trying to unmarshal the following JSON into a `[2][2]uint8` Go type fails for `github.com/go-json-experiment/json`, but works when using `encoding/json`.

Input JSON:
```json
[
	[1, 2],
	[3, 4]
]
```

Sample test program:
```go
package json_test

import (
	"testing"
	//"encoding/json"                    // go test PASS
	"github.com/go-json-experiment/json" // go test FAIL with error: json: cannot unmarshal JSON array into Go value of type [2]uint8
)

const rawInput = `
[
	[1, 2],
	[3, 4]
]`

func TestUnmarshal2(t *testing.T) {
	input := []byte(rawInput)
	var got [2][2]uint8
	want := [2][2]uint8{
		{1, 2},
		{3, 4},
	}
	if err := json.Unmarshal(input, &got); err != nil {
		t.Error(err)
	}
	if want != got {
		t.Errorf("mismatch: expected %v, got %v", want, got)
	}
}
```

Example run using `github.com/go-json-experiment/json`
```bash
$ go test --run TestUnmarshal2
--- FAIL: TestUnmarshal2 (0.00s)
    foo_test.go:22: json: cannot unmarshal JSON array into Go value of type [2]uint8
    foo_test.go:25: mismatch: expected [[1 2] [3 4]], got [[0 0] [0 0]]
FAIL
exit status 1
```

Example run using `encoding/json`
```bash
$ go test -v --run TestUnmarshal2
=== RUN   TestUnmarshal2
--- PASS: TestUnmarshal2 (0.00s)
PASS
ok  	json_test	0.001s
```

**Comment by dsnet** [comment]
Thanks for the report.

The unfortunate challenge is that the `byte` type in Go is just an alias for `uint8`. Thus, it is impossible from Go reflection to know whether the intent of something like `[16]byte` is supposed to be an array of 16 uint8 values or to be treated as a byte slice.

Empirically, we have found more cases of `[...]byte` where the intention is to be treated as bytes rather than as an array, which is what justified the change in behavior.

That said, if you do something like:
```go
type MyUint8 uint8
var got [2][2]MyUint8
want := [2][2]MyUint8{
	{1, 2},
	{3, 4},
}
```

Then it works as expected.

We will be providing an option that opts into the v1 behavior.

**Comment by mewmew** [comment]
Thanks for the explanation. It makes sense that the builtin type aliases cause problems in this regard.

Then I assume the same issue exist for `[n]int32` vs `[n]rune`?

> We will be providing an option that opts into the v1 behavior.

Much appreciated.

With kindness,
Robin

**Comment by dsnet** [comment]
`[...]rune` or `[]rune` is not treated specially as if it were a string. The v1 encoding/json package doesn't do this and I don't recall ever seeing requests for this behavior.

The https://pkg.go.dev/github.com/go-json-experiment/json/v1#FormatByteArrayAsArray option should do what you want.

Closing as completed.
